# Simple workflow for deploying static content to GitHub Pages
name: BuildApp

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
